STREAMING_PORT = "8554"
STREAMING_PATH = '/'
STREAMING_PROTOCOL = 'rtsp'
STREAMING_HOST = 'localhost'
STREAMING_URL = STREAMING_PROTOCOL + '://' + STREAMING_HOST + ':' + str(STREAMING_PORT) + STREAMING_PATH