# This workflow will install Python dependencies, run tests and lint with a variety of tools

name: Python QC

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        # xargs sudo apt-get install -y < apt-get-requirements.txt
        python -m pip install --upgrade pip
        pip install flake8 black
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --max-line-length=120 --statistics --ignore=E402,W503
    - name: Check code with black
      run: |
        black --check .
